crops <- read.csv("N_Content_expanded.csv")
fert <- read.csv("Ammonia_Lost.csv")
soil <- read.csv("denitrification.csv")

#read in pictures
diagram2 <- tags$a(href='https://acsess.onlinelibrary.wiley.com/doi/pdfdirect/10.2136/1991.managingnitrogen.c5',
                   tags$img(src='rotation_management.png', height = '375', width = '650', align = 'center'))



soil_drain <- soil %>% select(Soil.Drainage.Classification) %>% slice(1:5)

tabItem(tabName = "rotation",
        fluidRow(
          box(title = "Nitrogen Budget: Rotation Management",
              status = "info",
              solidHeader = T,
              width = 6,
              p("The Rotation Management: Nitrate Leaching Calculator uses the conservation of mass to estimate potential nitrogen leaching. 
                    for comparison of different years in a rotation on the same field. 
                    The tool relies on user knowledge of various inputs such as yield, fertilizer, soil type, etc.
                    Other factors are assigned using tables and other assumptions outlined in Meisenger and Randall (1991)."),
              p(strong("Using this tool:")),
              p("1. Enter information about soils and other environmental conditions."),
              p("2. Enter information about crop and nitrogen inputs for up to two management scenarios."),
              p("3. If field is irrigated and/or cover crop was grown, click yes to enter information."),
              p("4. If simulating the impact of altering a management practice on a portion of the field, enter the acreage for each scenario. 
                    The calculator will estimate a weighted leaching loss/nitrate concentration based on the acreage."),
              p("5. Scroll down to the bottom of the page to view your Nitrogen Budget."),
              p("For more information about various data inputs, hover over the 'i' next to the field name."),
          ),
          box(title = "",
              status = "info",
              solidHeader = F,
              width = 6,
              div(diagram2)),
        ),
        fluidRow(
                box(title = "Soil",
                    solidHeader = T,
                    width = 6,
                    status = "primary",
                    column(6,
                           strong("Soil Organic Matter Content"),
                           span(shiny::icon("info-circle"),
                                id = "info_soilOrgMatCont"),
                           selectInput("soilType_RM",
                                       NULL,
                                       choices = soil$Organic.Matter.Content,
                                       selected = 1),
                           tippy::tippy_this(elementId = "info_soilOrgMatCont",
                                             tooltip = "<span style='font-size:16px;'>Select the percent soil organic matter<span>",
                                             placement = "right")
                    ),
                    column(6,
                           strong("Soil Drainage Classification"),
                           span(shiny::icon("info-circle"),
                                id = "info_drainClass"),
                           selectInput("drainClass_RM",
                                       NULL,
                                       choices = soil_drain$Soil.Drainage.Classification,
                                       selected = 1),
                           tippy::tippy_this(elementId = "info_drainClass",
                                             tooltip = "<span style='font-size:16px;'>Select soil drainage classification<span>",
                                             placement = "right")
                    )
                )
        ),
        fluidRow(
           box(title = "Year 1",
               width = 12,
               solidHeader = T,
               status = "warning",
               column(4,
                      box(title = "Environment",
                          solidHeader = T,
                          status = "primary",
                          width = 12,
                      fluidRow(
                      box(title = "Change in N Storage",
                          solidHeader = T,
                          status = "info",
                          width = 12,
                          column(6,
                                 strong("Change in Inorganic N"),
                                 span(shiny::icon("info-circle"),
                                      id = "info_inoN"),
                                 numericInput("inoN_RM_yr1",
                                              NULL,
                                              value = 0,
                                              min = 0),
                                 tippy::tippy_this(elementId = "info_inoN",
                                                   tooltip = "<span style='font-size:16px;'>If you have know the change in NO3 and NH4 enter here, otherwise assume '0'<span>",
                                                   placement = "right")
                          ),
                          column(6,
                                 strong("Change in Organic N"),
                                 span(shiny::icon("info-circle"),
                                      id = "info_orgN"),
                                 numericInput("Change_orgN_RM_yr1",
                                              NULL,
                                              value = 0,
                                              min = 0),
                                 tippy::tippy_this(elementId = "info_orgN",
                                                   tooltip = "<span style='font-size:16px;'>Soil organic matter content used to estimate change in organic N storage, if organic N measured can replace default value<span>",
                                                   placement = "right")
                          )
                      )
                      ),
                fluidRow(
                       box(title = "Precipitation",
                           solidHeader = T,
                           status = "info",
                           width = 12,
                           column(6,
                                  strong("Nitrate-N Concentration (mg/L)"),
                                  span(shiny::icon("info-circle"),
                                       id = "info_precip"),
                                  numericInput("precip_RM_yr1",
                                               NULL,
                                               value = 0.5,
                                               min = 0),
                                  tippy::tippy_this(elementId = "info_precip",
                                                    tooltip = "<span style='font-size:16px;'>Enter the annual average concentration of nitrate-N in precipitation for your area if known. Default for Wisconsin is 0.5 mg/L nitrate-N.<span>",
                                                    placement = "right")
                           ),
                           column(6,
                                  strong("Annual Total (inches)"),
                                  span(shiny::icon("info-circle"),
                                       id = "info_inchesPre"),
                                  numericInput("InchPre_RM_yr1",
                                               NULL,
                                               value = 32,
                                               min = 0),
                                  tippy::tippy_this(elementId = "info_inchesPre",
                                                    tooltip = "<span style='font-size:16px;'>Calculate this by entering irrigation water nitrate and inches applied<span>",
                                                    placement = "right")
                           )
                           )
                       ),
                         box(title = "Irrigation",
                             solidHeader = T,
                             status = "info",
                             width = 12,
                             column(width = 6,
                                    h3("Is this field irrigated?"),
                                    span(shiny::icon("info-circle"),
                                         id = "info_irr"),
                                    radioButtons("irr_yr1",
                                                 NULL,
                                                 choices = list("No" = 0,
                                                                "Yes" = 1)
                                    ),
                                    tippy::tippy_this(elementId = "irr",
                                                      tooltip = "<span style='font-size:16px;'>If this field was irrigated, click 'Yes'<span>",
                                                      placement = "right")
                             ),
                             uiOutput("irrigation_Qs_yr1")
                         )
                        )
                       ),
               column(8,
                      box(title = "Management Scenario",
                          solidHeader = T,
                          status = "danger",
                          width = 12,
                          fluidRow(
                                  column(6,
                                        box(title = "Crop Information",
                                             solidHeader = T,
                                             status = "info",
                                             width = 12,
                                        fluidRow(
                                        column(6, 
                                         strong("Crop Type"),
                                         span(shiny::icon("info-circle"), 
                                              id = "info_crop_yr1"),
                                         selectInput("crop_yr1",
                                                     NULL,
                                                     choices = crops$Crop.Type,
                                                     selected = 1),
                                         tippy::tippy_this(elementId = "info_crop_yr1",
                                                           tooltip = "<span style='font-size:16px;'>Select crop type for each field or portion of field<span>",
                                                           placement = "right")
                                         ),
                                         column(6,
                                                strong("Harvest Material / Units"),
                                                span(shiny::icon("info-circle"), 
                                                     id = "info_units1"),
                                                uiOutput("year1CropUnits"),
                                                tippy::tippy_this(elementId = "info_units1",
                                                                  tooltip = "<span style='font-size:16px;'>Type of harvested material and units of measure can be selected once a crop type is selected.<span>",
                                                                  placement = "right")
                                         )
                                        ),
                                        fluidRow(
                                            column(6,
                                               strong("Year 1 Yield"),
                                               span(shiny::icon("info-circle"),
                                                                     id = "info_yield_yr1"),
                                                                numericInput("yield_yr1",
                                                                             NULL,
                                                                             value = 0,
                                                                             min = 0),
                                                                tippy::tippy_this(elementId = "info_yield_yr1",
                                                                                  tooltip = "<span style='font-size:16px;'>Enter yield for each field or portion of field<span>",
                                                                                  placement = "right")
                                                         ),
                                                         column(6,
                                                                strong("Acres"),
                                                                span(shiny::icon("info-circle"),
                                                                     id = "info_acres_yr1"),
                                                                numericInput("acres_yr1",
                                                                             NULL,
                                                                             value = 0,
                                                                             min = 0),
                                                                tippy::tippy_this(elementId = "info_acres_yr1",
                                                                                  tooltip = "<span style='font-size:16px;'>Enter size of field/portion of field. Only used to calculate combined leachable N<span>",
                                                                                  placement = "right")
                                                         )
                                                 )
                                             ),
                                        box(title = "Cover Crop Residue (lbs N/acre)",
                                             solidHeader = T,
                                             status = "info",
                                             width = 12,
                                             column(width = 6,
                                                    h3("Did you plant a cover crop?"),
                                                    span(shiny::icon("info-circle"),
                                                         id = "info_cover_yr1"),
                                                    radioButtons("cp_yr1",
                                                                 NULL,
                                                                 choices = list("No" = 0,
                                                                                "Yes" = 1)
                                                    ),
                                                    tippy::tippy_this(elementId = "info_cover_yr1",
                                                                      tooltip = "<span style='font-size:20px;'>If cover crop was grown click yes to enter information, otherwise leave as 'no'<span>",
                                                                      placement = "right")
                                             ),
                                             uiOutput("plot_cover_yr1")

                                         )


                          ),
                      column(6,
                             box(title = "Nitrogen Inputs",
                                 solidHeader = T,
                                 status = "info",
                                 width = 12,
                                 box(title = "Fertilizer",
                                     solidHeader = T,
                                     status = "info",
                                     width = 12,
                                     fluidRow(
                                             column(12,
                                                    strong("Form"),
                                                    span(shiny::icon("info-circle"),
                                                         id = "info_fertform_yr1"),
                                                    selectInput("fertform_yr1",
                                                                NULL,
                                                                choices = fert$Fertilizer.N.Source,
                                                                selected = 1),
                                                    tippy::tippy_this(elementId = "info_fertform_yr1",
                                                                      tooltip = "<span style='font-size:16px;'>Enter total amount of nitrogen fertilizer applied (lbs N/acre)<span>",
                                                                      placement = "right")
                                             )
                                     ),
                                     fluidRow(
                                             column(6,
                                                    strong("Application Method"),
                                                    span(shiny::icon("info-circle"),
                                                         id = "info_fertApp_yr1"),
                                                    uiOutput("fert_selection_yr1"),
                                                    tippy::tippy_this(elementId = "info_fertApp_yr1",
                                                                      tooltip = "<span style='font-size:16px;'>Select the application method<span>",
                                                                      placement = "right")
                                             ),
                                             column(6,
                                                    strong("Rate (lbs N/acre)"),
                                                    span(shiny::icon("info-circle"),
                                                         id = "info_fert_yr1"),
                                                    numericInput("fert_yr1",
                                                                 NULL,
                                                                 value = 0,
                                                                 min = 0),
                                                    tippy::tippy_this(elementId = "info_fert_yr1",
                                                                      tooltip = "<span style='font-size:16px;'>Enter total amount of nitrogen fertilizer applied (lbs N/acre)<span>",
                                                                      placement = "right")
                                             )
                                     )
                                 ),
                                 box(title = "Manure and Symbiotic N Fixation (Legumes)",
                                     solidHeader = T,
                                     status = "info",
                                     width = 12,
                                     column(6,
                                            strong("Manure"),
                                            span(shiny::icon("info-circle"),
                                                 id = "info_man_yr1"),
                                            numericInput("man_yr1",
                                                         NULL,
                                                         value = 0,
                                                         min = 0),
                                            tippy::tippy_this(elementId = "info_man_yr1",
                                                              tooltip = "<span style='font-size:16px;'>First year available N and any N credits from previous years<span>",
                                                              placement = "right")
                                     ),
                                     column(6,
                                            strong("Symbiotic N Fixation (Legumes)"),
                                            span(shiny::icon("info-circle"),
                                                 id = "info_leg_yr1"),
                                            numericInput("leg_yr1",
                                                         NULL,
                                                         value = 0,
                                                         min = 0),
                                            tippy::tippy_this(elementId = "info_leg_yr1",
                                                              tooltip = "<span style='font-size:16px;'>If no legumes grown, this value should be 0.<br/>If legumes grown, enter pounds of nitrogen produced from growing legumes<span>",
                                                              placement = "right")
                                     )
                                 )
                             )
                      ))))
               
               )),
        fluidRow(
                box(title = "Year 2",
                    width = 12,
                    solidHeader = T,
                    status = "warning",
                    column(4,
                           box(title = "Environment",
                               solidHeader = T,
                               status = "primary",
                               width = 12,
                               fluidRow(
                                       box(title = "Change in N Storage",
                                           solidHeader = T,
                                           status = "info",
                                           width = 12,
                                           column(6,
                                                  strong("Change in Inorganic N"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_inoN"),
                                                  numericInput("inoN_RM_yr2",
                                                               NULL,
                                                               value = 0,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_inoN",
                                                                    tooltip = "<span style='font-size:16px;'>If you have know the change in NO3 and NH4 enter here, otherwise assume '0'<span>",
                                                                    placement = "right")
                                           ),
                                           column(6,
                                                  strong("Change in Organic N"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_orgN"),
                                                  numericInput("Change_orgN_RM_yr2",
                                                               NULL,
                                                               value = 0,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_orgN",
                                                                    tooltip = "<span style='font-size:16px;'>Soil organic matter content used to estimate change in organic N storage, if organic N measured can replace default value<span>",
                                                                    placement = "right")
                                           )
                                       )
                               ),
                               fluidRow(
                                       box(title = "Precipitation",
                                           solidHeader = T,
                                           status = "info",
                                           width = 12,
                                           column(6,
                                                  strong("Nitrate-N Concentration (mg/L)"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_precip"),
                                                  numericInput("precip_RM_yr2",
                                                               NULL,
                                                               value = 0.5,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_precip",
                                                                    tooltip = "<span style='font-size:16px;'>Enter the annual average concentration of nitrate-N in precipitation for your area if known. Default for Wisconsin is 0.5 mg/L nitrate-N.<span>",
                                                                    placement = "right")
                                           ),
                                           column(6,
                                                  strong("Annual Total (inches)"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_inchesPre"),
                                                  numericInput("InchPre_RM_yr2",
                                                               NULL,
                                                               value = 32,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_inchesPre",
                                                                    tooltip = "<span style='font-size:16px;'>Calculate this by entering irrigation water nitrate and inches applied<span>",
                                                                    placement = "right")
                                           )
                                       )
                               ),
                               box(title = "Irrigation",
                                   solidHeader = T,
                                   status = "info",
                                   width = 12,
                                   column(width = 6,
                                          h3("Is this field irrigated?"),
                                          span(shiny::icon("info-circle"),
                                               id = "info_irr"),
                                          radioButtons("irr_yr2",
                                                       NULL,
                                                       choices = list("No" = 0,
                                                                      "Yes" = 1)
                                          ),
                                          tippy::tippy_this(elementId = "irr",
                                                            tooltip = "<span style='font-size:16px;'>If this field was irrigated, click 'Yes'<span>",
                                                            placement = "right")
                                   ),
                                   uiOutput("irrigation_Qs_yr2")
                               )
                           )
                    ),
                    column(8,
                           box(title = "Management Scenario",
                               solidHeader = T,
                               status = "danger",
                               width = 12,
                               fluidRow(
                                       column(6,
                                              box(title = "Crop Information",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  fluidRow(
                                                          column(6,
                                                                 strong("Crop Type"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_crop_yr2"),
                                                                 selectInput("crop_yr2",
                                                                             NULL,
                                                                             choices = crops$Crop.Type,
                                                                             selected = 1),
                                                                 tippy::tippy_this(elementId = "info_crop_yr2",
                                                                                   tooltip = "<span style='font-size:16px;'>Select crop type for each field or portion of field<span>",
                                                                                   placement = "right")
                                                          ),
                                                          column(6,
                                                                 strong("Harvest Material / Units"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_units_yr2"),
                                                                 uiOutput("year2CropUnits"),
                                                                 tippy::tippy_this(elementId = "info_units_yr2",
                                                                                   tooltip = "<span style='font-size:16px;'>Type of harvested material and units of measure can be selected once a crop type is selected.<span>",
                                                                                   placement = "right")
                                                          )
                                                  ),
                                                  fluidRow(
                                                          column(6,
                                                                 strong("Year 1 Yield"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_yield_yr2"),
                                                                 numericInput("yield_yr2",
                                                                              NULL,
                                                                              value = 0,
                                                                              min = 0),
                                                                 tippy::tippy_this(elementId = "info_yield_yr2",
                                                                                   tooltip = "<span style='font-size:16px;'>Enter yield for each field or portion of field<span>",
                                                                                   placement = "right")
                                                          ),
                                                          column(6,
                                                                 strong("Acres"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_acres_yr2"),
                                                                 numericInput("acres_yr2",
                                                                              NULL,
                                                                              value = 0,
                                                                              min = 0),
                                                                 tippy::tippy_this(elementId = "info_acres_yr2",
                                                                                   tooltip = "<span style='font-size:16px;'>Enter size of field/portion of field. Only used to calculate combined leachable N<span>",
                                                                                   placement = "right")
                                                          )
                                                  )
                                              ),
                                              box(title = "Cover Crop Residue (lbs N/acre)",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  column(width = 6,
                                                         h3("Did you plant a cover crop?"),
                                                         span(shiny::icon("info-circle"),
                                                              id = "info_cover_yr2"),
                                                         radioButtons("cp_yr2",
                                                                      NULL,
                                                                      choices = list("No" = 0,
                                                                                     "Yes" = 1)
                                                         ),
                                                         tippy::tippy_this(elementId = "info_cover_yr2",
                                                                           tooltip = "<span style='font-size:20px;'>If cover crop was grown click yes to enter information, otherwise leave as 'no'<span>",
                                                                           placement = "right")
                                                  ),
                                                  uiOutput("plot_cover_yr2")

                                              )


                                       ),
                                       column(6,
                                              box(title = "Nitrogen Inputs",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  box(title = "Fertilizer",
                                                      solidHeader = T,
                                                      status = "info",
                                                      width = 12,
                                                      fluidRow(
                                                              column(12,
                                                                     strong("Form"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fertform_yr2"),
                                                                     selectInput("fertform_yr2",
                                                                                 NULL,
                                                                                 choices = fert$Fertilizer.N.Source,
                                                                                 selected = 1),
                                                                     tippy::tippy_this(elementId = "info_fertform_yr2",
                                                                                       tooltip = "<span style='font-size:16px;'>Enter total amount of nitrogen fertilizer applied (lbs N/acre)<span>",
                                                                                       placement = "right")
                                                              )
                                                      ),
                                                      fluidRow(
                                                              column(6,
                                                                     strong("Application Method"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fertApp_yr2"),
                                                                     uiOutput("fert_selection_yr2"),
                                                                     tippy::tippy_this(elementId = "info_fertApp_yr2",
                                                                                       tooltip = "<span style='font-size:16px;'>Select the application method<span>",
                                                                                       placement = "right")
                                                              ),
                                                              column(6,
                                                                     strong("Rate (lbs N/acre)"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fert_yr2"),
                                                                     numericInput("fert_yr2",
                                                                                  NULL,
                                                                                  value = 0,
                                                                                  min = 0),
                                                                     tippy::tippy_this(elementId = "info_fert_yr2",
                                                                                       tooltip = "<span style='font-size:16px;'>Enter total amount of nitrogen fertilizer applied (lbs N/acre)<span>",
                                                                                       placement = "right")
                                                              )
                                                      )
                                                  ),
                                                  box(title = "Manure and Symbiotic N Fixation (Legumes)",
                                                      solidHeader = T,
                                                      status = "info",
                                                      width = 12,
                                                      column(6,
                                                             strong("Manure"),
                                                             span(shiny::icon("info-circle"),
                                                                  id = "info_man_yr2"),
                                                             numericInput("man_yr2",
                                                                          NULL,
                                                                          value = 0,
                                                                          min = 0),
                                                             tippy::tippy_this(elementId = "info_man_yr2",
                                                                               tooltip = "<span style='font-size:16px;'>First year available N and any N credits from previous years<span>",
                                                                               placement = "right")
                                                      ),
                                                      column(6,
                                                             strong("Symbiotic N Fixation (Legumes)"),
                                                             span(shiny::icon("info-circle"),
                                                                  id = "info_leg_yr2"),
                                                             numericInput("leg_yr2",
                                                                          NULL,
                                                                          value = 0,
                                                                          min = 0),
                                                             tippy::tippy_this(elementId = "info_leg_yr2",
                                                                               tooltip = "<span style='font-size:16px;'>If no legumes grown, this value should be 0.<br/>If legumes grown, enter pounds of nitrogen produced from growing legumes<span>",
                                                                               placement = "right")
                                                      )
                                                  )
                                              )
                                       ))))

                )),
        fluidRow(
                box(title = "Year 3",
                    width = 12,
                    solidHeader = T,
                    status = "warning",
                    column(4,
                           box(title = "Environment",
                               solidHeader = T,
                               status = "primary",
                               width = 12,
                               fluidRow(
                                       box(title = "Change in N Storage",
                                           solidHeader = T,
                                           status = "info",
                                           width = 12,
                                           column(6,
                                                  strong("Change in Inorganic N"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_inoN"),
                                                  numericInput("inoN_RM_yr3",
                                                               NULL,
                                                               value = 0,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_inoN",
                                                                    tooltip = "<span style='font-size:16px;'>If you have know the change in NO3 and NH4 enter here, otherwise assume '0'<span>",
                                                                    placement = "right")
                                           ),
                                           column(6,
                                                  strong("Change in Organic N"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_orgN"),
                                                  numericInput("Change_orgN_RM_yr3",
                                                               NULL,
                                                               value = 0,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_orgN",
                                                                    tooltip = "<span style='font-size:16px;'>Soil organic matter content used to estimate change in organic N storage, if organic N measured can replace default value<span>",
                                                                    placement = "right")
                                           )
                                       )
                               ),
                               fluidRow(
                                       box(title = "Precipitation",
                                           solidHeader = T,
                                           status = "info",
                                           width = 12,
                                           column(6,
                                                  strong("Nitrate-N Concentration (mg/L)"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_precip"),
                                                  numericInput("precip_RM_yr3",
                                                               NULL,
                                                               value = 0.5,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_precip",
                                                                    tooltip = "<span style='font-size:16px;'>Enter the annual average concentration of nitrate-N in precipitation for your area if known. Default for Wisconsin is 0.5 mg/L nitrate-N.<span>",
                                                                    placement = "right")
                                           ),
                                           column(6,
                                                  strong("Annual Total (inches)"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_inchesPre"),
                                                  numericInput("InchPre_RM_yr3",
                                                               NULL,
                                                               value = 32,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_inchesPre",
                                                                    tooltip = "<span style='font-size:16px;'>Calculate this by entering irrigation water nitrate and inches applied<span>",
                                                                    placement = "right")
                                           )
                                       )
                               ),
                               box(title = "Irrigation",
                                   solidHeader = T,
                                   status = "info",
                                   width = 12,
                                   column(width = 6,
                                          h3("Is this field irrigated?"),
                                          span(shiny::icon("info-circle"),
                                               id = "info_irr"),
                                          radioButtons("irr_yr3",
                                                       NULL,
                                                       choices = list("No" = 0,
                                                                      "Yes" = 1)
                                          ),
                                          tippy::tippy_this(elementId = "irr",
                                                            tooltip = "<span style='font-size:16px;'>If this field was irrigated, click 'Yes'<span>",
                                                            placement = "right")
                                   ),
                                   uiOutput("irrigation_Qs_yr3")
                               )
                           )
                    ),
                    column(8,
                           box(title = "Management Scenario",
                               solidHeader = T,
                               status = "danger",
                               width = 12,
                               fluidRow(
                                       column(6,
                                              box(title = "Crop Information",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  fluidRow(
                                                          column(6,
                                                                 strong("Crop Type"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_crop_yr3"),
                                                                 selectInput("crop_yr3",
                                                                             NULL,
                                                                             choices = crops$Crop.Type,
                                                                             selected = 1),
                                                                 tippy::tippy_this(elementId = "info_crop_yr3",
                                                                                   tooltip = "<span style='font-size:16px;'>Select crop type for each field or portion of field<span>",
                                                                                   placement = "right")
                                                          ),
                                                          column(6,
                                                                 strong("Harvest Material / Units"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_units3"),
                                                                 uiOutput("year3CropUnits"),
                                                                 tippy::tippy_this(elementId = "info_units3",
                                                                                   tooltip = "<span style='font-size:16px;'>Type of harvested material and units of measure can be selected once a crop type is selected.<span>",
                                                                                   placement = "right")
                                                          )
                                                  ),
                                                  fluidRow(
                                                          column(6,
                                                                 strong("Year 3 Yield"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_yield_yr3"),
                                                                 numericInput("yield_yr3",
                                                                              NULL,
                                                                              value = 0,
                                                                              min = 0),
                                                                 tippy::tippy_this(elementId = "info_yield_yr3",
                                                                                   tooltip = "<span style='font-size:16px;'>Enter yield for each field or portion of field<span>",
                                                                                   placement = "right")
                                                          ),
                                                          column(6,
                                                                 strong("Acres"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_acres_yr3"),
                                                                 numericInput("acres_yr3",
                                                                              NULL,
                                                                              value = 0,
                                                                              min = 0),
                                                                 tippy::tippy_this(elementId = "info_acres_yr3",
                                                                                   tooltip = "<span style='font-size:16px;'>Enter size of field/portion of field. Only used to calculate combined leachable N<span>",
                                                                                   placement = "right")
                                                          )
                                                  )
                                              ),
                                              box(title = "Cover Crop Residue (lbs N/acre)",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  column(width = 6,
                                                         h3("Did you plant a cover crop?"),
                                                         span(shiny::icon("info-circle"),
                                                              id = "info_cover_yr3"),
                                                         radioButtons("cp_yr3",
                                                                      NULL,
                                                                      choices = list("No" = 0,
                                                                                     "Yes" = 1)
                                                         ),
                                                         tippy::tippy_this(elementId = "info_cover_yr3",
                                                                           tooltip = "<span style='font-size:20px;'>If cover crop was grown click yes to enter information, otherwise leave as 'no'<span>",
                                                                           placement = "right")
                                                  ),
                                                  uiOutput("plot_cover_yr3")

                                              )


                                       ),
                                       column(6,
                                              box(title = "Nitrogen Inputs",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  box(title = "Fertilizer",
                                                      solidHeader = T,
                                                      status = "info",
                                                      width = 12,
                                                      fluidRow(
                                                              column(12,
                                                                     strong("Form"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fertform_yr3"),
                                                                     selectInput("fertform_yr3",
                                                                                 NULL,
                                                                                 choices = fert$Fertilizer.N.Source,
                                                                                 selected = 1),
                                                                     tippy::tippy_this(elementId = "info_fertform_yr3",
                                                                                       tooltip = "<span style='font-size:16px;'>Enter total amount of nitrogen fertilizer applied (lbs N/acre)<span>",
                                                                                       placement = "right")
                                                              )
                                                      ),
                                                      fluidRow(
                                                              column(6,
                                                                     strong("Application Method"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fertApp_yr3"),
                                                                     uiOutput("fert_selection_yr3"),
                                                                     tippy::tippy_this(elementId = "info_fertApp_yr3",
                                                                                       tooltip = "<span style='font-size:16px;'>Select the application method<span>",
                                                                                       placement = "right")
                                                              ),
                                                              column(6,
                                                                     strong("Rate (lbs N/acre)"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fert_yr3"),
                                                                     numericInput("fert_yr3",
                                                                                  NULL,
                                                                                  value = 0,
                                                                                  min = 0),
                                                                     tippy::tippy_this(elementId = "info_fert_yr3",
                                                                                       tooltip = "<span style='font-size:16px;'>Enter total amount of nitrogen fertilizer applied (lbs N/acre)<span>",
                                                                                       placement = "right")
                                                              )
                                                      )
                                                  ),
                                                  box(title = "Manure and Symbiotic N Fixation (Legumes)",
                                                      solidHeader = T,
                                                      status = "info",
                                                      width = 12,
                                                      column(6,
                                                             strong("Manure"),
                                                             span(shiny::icon("info-circle"),
                                                                  id = "info_man_yr3"),
                                                             numericInput("man_yr3",
                                                                          NULL,
                                                                          value = 0,
                                                                          min = 0),
                                                             tippy::tippy_this(elementId = "info_man_yr3",
                                                                               tooltip = "<span style='font-size:16px;'>First year available N and any N credits from previous years<span>",
                                                                               placement = "right")
                                                      ),
                                                      column(6,
                                                             strong("Symbiotic N Fixation (Legumes)"),
                                                             span(shiny::icon("info-circle"),
                                                                  id = "info_leg_yr3"),
                                                             numericInput("leg_yr3",
                                                                          NULL,
                                                                          value = 0,
                                                                          min = 0),
                                                             tippy::tippy_this(elementId = "info_leg_yr3",
                                                                               tooltip = "<span style='font-size:16px;'>If no legumes grown, this value should be 0.<br/>If legumes grown, enter pounds of nitrogen produced from growing legumes<span>",
                                                                               placement = "right")
                                                      )
                                                  )
                                              )
                                       ))))

                )),
        fluidRow(
                box(title = "Year 4",
                    width = 12,
                    solidHeader = T,
                    status = "warning",
                    column(4,
                           box(title = "Environment",
                               solidHeader = T,
                               status = "primary",
                               width = 12,
                               fluidRow(
                                       box(title = "Change in N Storage",
                                           solidHeader = T,
                                           status = "info",
                                           width = 12,
                                           column(6,
                                                  strong("Change in Inorganic N"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_inoN"),
                                                  numericInput("inoN_RM_yr4",
                                                               NULL,
                                                               value = 0,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_inoN",
                                                                    tooltip = "<span style='font-size:16px;'>If you have know the change in NO3 and NH4 enter here, otherwise assume '0'<span>",
                                                                    placement = "right")
                                           ),
                                           column(6,
                                                  strong("Change in Organic N"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_orgN"),
                                                  numericInput("Change_orgN_RM_yr4",
                                                               NULL,
                                                               value = 0,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_orgN",
                                                                    tooltip = "<span style='font-size:16px;'>Soil organic matter content used to estimate change in organic N storage, if organic N measured can replace default value<span>",
                                                                    placement = "right")
                                           )
                                       )
                               ),
                               fluidRow(
                                       box(title = "Precipitation",
                                           solidHeader = T,
                                           status = "info",
                                           width = 12,
                                           column(6,
                                                  strong("Nitrate-N Concentration (mg/L)"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_precip"),
                                                  numericInput("precip_RM_yr4",
                                                               NULL,
                                                               value = 0.5,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_precip",
                                                                    tooltip = "<span style='font-size:16px;'>Enter the annual average concentration of nitrate-N in precipitation for your area if known. Default for Wisconsin is 0.5 mg/L nitrate-N.<span>",
                                                                    placement = "right")
                                           ),
                                           column(6,
                                                  strong("Annual Total (inches)"),
                                                  span(shiny::icon("info-circle"),
                                                       id = "info_inchesPre"),
                                                  numericInput("InchPre_RM_yr4",
                                                               NULL,
                                                               value = 32,
                                                               min = 0),
                                                  tippy::tippy_this(elementId = "info_inchesPre",
                                                                    tooltip = "<span style='font-size:16px;'>Calculate this by entering irrigation water nitrate and inches applied<span>",
                                                                    placement = "right")
                                           )
                                       )
                               ),
                               box(title = "Irrigation",
                                   solidHeader = T,
                                   status = "info",
                                   width = 12,
                                   column(width = 6,
                                          h3("Is this field irrigated?"),
                                          span(shiny::icon("info-circle"),
                                               id = "info_irr"),
                                          radioButtons("irr_yr4",
                                                       NULL,
                                                       choices = list("No" = 0,
                                                                      "Yes" = 1)
                                          ),
                                          tippy::tippy_this(elementId = "irr",
                                                            tooltip = "<span style='font-size:16px;'>If this field was irrigated, click 'Yes'<span>",
                                                            placement = "right")
                                   ),
                                   uiOutput("irrigation_Qs_yr4")
                               )
                           )
                    ),
                    column(8,
                           box(title = "Management Scenario",
                               solidHeader = T,
                               status = "danger",
                               width = 12,
                               fluidRow(
                                       column(6,
                                              box(title = "Crop Information",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  fluidRow(
                                                          column(6,
                                                                 strong("Crop Type"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_crop_yr4"),
                                                                 selectInput("crop_yr4",
                                                                             NULL,
                                                                             choices = crops$Crop.Type,
                                                                             selected = 1),
                                                                 tippy::tippy_this(elementId = "info_crop_yr4",
                                                                                   tooltip = "<span style='font-size:16px;'>Select crop type for each field or portion of field<span>",
                                                                                   placement = "right")
                                                          ),
                                                          column(6,
                                                                 strong("Harvest Material / Units"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_units4"),
                                                                 uiOutput("year4CropUnits"),
                                                                 tippy::tippy_this(elementId = "info_units4",
                                                                                   tooltip = "<span style='font-size:16px;'>Type of harvested material and units of measure can be selected once a crop type is selected.<span>",
                                                                                   placement = "right")
                                                          )
                                                  ),
                                                  fluidRow(
                                                          column(6,
                                                                 strong("Year 4 Yield"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_yield_yr4"),
                                                                 numericInput("yield_yr4",
                                                                              NULL,
                                                                              value = 0,
                                                                              min = 0),
                                                                 tippy::tippy_this(elementId = "info_yield_yr4",
                                                                                   tooltip = "<span style='font-size:16px;'>Enter yield for each field or portion of field<span>",
                                                                                   placement = "right")
                                                          ),
                                                          column(6,
                                                                 strong("Acres"),
                                                                 span(shiny::icon("info-circle"),
                                                                      id = "info_acres_yr4"),
                                                                 numericInput("acres_yr4",
                                                                              NULL,
                                                                              value = 0,
                                                                              min = 0),
                                                                 tippy::tippy_this(elementId = "info_acres_yr4",
                                                                                   tooltip = "<span style='font-size:16px;'>Enter size of field/portion of field. Only used to calculate combined leachable N<span>",
                                                                                   placement = "right")
                                                          )
                                                  )
                                              ),
                                              box(title = "Cover Crop Residue (lbs N/acre)",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  column(width = 6,
                                                         h3("Did you plant a cover crop?"),
                                                         span(shiny::icon("info-circle"),
                                                              id = "info_cover_yr4"),
                                                         radioButtons("cp_yr4",
                                                                      NULL,
                                                                      choices = list("No" = 0,
                                                                                     "Yes" = 1)
                                                         ),
                                                         tippy::tippy_this(elementId = "info_cover_yr4",
                                                                           tooltip = "<span style='font-size:20px;'>If cover crop was grown click yes to enter information, otherwise leave as 'no'<span>",
                                                                           placement = "right")
                                                  ),
                                                  uiOutput("plot_cover_yr4")

                                              )


                                       ),
                                       column(6,
                                              box(title = "Nitrogen Inputs",
                                                  solidHeader = T,
                                                  status = "info",
                                                  width = 12,
                                                  box(title = "Fertilizer",
                                                      solidHeader = T,
                                                      status = "info",
                                                      width = 12,
                                                      fluidRow(
                                                              column(12,
                                                                     strong("Form"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fertform_yr4"),
                                                                     selectInput("fertform_yr4",
                                                                                 NULL,
                                                                                 choices = fert$Fertilizer.N.Source,
                                                                                 selected = 1),
                                                                     tippy::tippy_this(elementId = "info_fertform_yr4",
                                                                                       tooltip = "<span style='font-size:16px;'>Enter total amount of nitrogen fertilizer applied (lbs N/acre)<span>",
                                                                                       placement = "right")
                                                              )
                                                      ),
                                                      fluidRow(
                                                              column(6,
                                                                     strong("Application Method"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fertApp_yr4"),
                                                                     uiOutput("fert_selection_yr4"),
                                                                     tippy::tippy_this(elementId = "info_fertApp_yr4",
                                                                                       tooltip = "<span style='font-size:16px;'>Select the application method<span>",
                                                                                       placement = "right")
                                                              ),
                                                              column(6,
                                                                     strong("Rate (lbs N/acre)"),
                                                                     span(shiny::icon("info-circle"),
                                                                          id = "info_fert_yr4"),
                                                                     numericInput("fert_yr4",
                                                                                  NULL,
                                                                                  value = 0,
                                                                                  min = 0),
                                                                     tippy::tippy_this(elementId = "info_fert_yr4",
                                                                                       tooltip = "<span style='font-size:16px;'>Enter total amount of nitrogen fertilizer applied (lbs N/acre)<span>",
                                                                                       placement = "right")
                                                              )
                                                      )
                                                  ),
                                                  box(title = "Manure and Symbiotic N Fixation (Legumes)",
                                                      solidHeader = T,
                                                      status = "info",
                                                      width = 12,
                                                      column(6,
                                                             strong("Manure"),
                                                             span(shiny::icon("info-circle"),
                                                                  id = "info_man_yr4"),
                                                             numericInput("man_yr4",
                                                                          NULL,
                                                                          value = 0,
                                                                          min = 0),
                                                             tippy::tippy_this(elementId = "info_man_yr4",
                                                                               tooltip = "<span style='font-size:16px;'>First year available N and any N credits from previous years<span>",
                                                                               placement = "right")
                                                      ),
                                                      column(6,
                                                             strong("Symbiotic N Fixation (Legumes)"),
                                                             span(shiny::icon("info-circle"),
                                                                  id = "info_legyr4"),
                                                             numericInput("leg_yr4",
                                                                          NULL,
                                                                          value = 0,
                                                                          min = 0),
                                                             tippy::tippy_this(elementId = "info_leg_yr4",
                                                                               tooltip = "<span style='font-size:16px;'>If no legumes grown, this value should be 0.<br/>If legumes grown, enter pounds of nitrogen produced from growing legumes<span>",
                                                                               placement = "right")
                                                      )
                                                  )
                                              )
                                       ))))

                )),
        fluidRow(
          box(title = "Ouputs",
              width = 12,
              solidHeader = T,
              status = "success",
              column(8,
                     box(title = "Crop Information",
                         solidHeader = T,
                         status = "info",
                         width = 12,
                         rHandsontableOutput("rhot1_yr4")),
                     box(title = "Inputs",
                         solidHeader = T,
                         status = "info",
                         width = 12,
                         rHandsontableOutput("rhot2_yr4")),
                     box(title = "Outputs",
                         solidHeader = T,
                         status = "info",
                         width = 12,
                         rHandsontableOutput("rhot3_yr4")),
                     box(title = "Change in N Storage",
                         solidHeader = T,
                         status = "info",
                         width = 12,
                         rHandsontableOutput("rhot4_yr4")),
                     box(title = "Cover Crop Residue",
                         solidHeader = T,
                         status = "info",
                         width = 12,
                         rHandsontableOutput("rhot5_yr4"))
                     
                     
              ),
              column(4,
                     box(title = "Final Outputs of some sorts",
                         width = 12, 
                         solidHeader = T,
                         status = "warning",
                         paste("Some Numbers")
                         )
              )
              )
        )
)