define({
  root: ({
    selectFeatures: "By Shape",
    selectByAttribute: "By Text",
    searchLayer: "Select samples by",
    selectFeaturesBy: "Select samples by",
    selectSpatial: "By Point",
    search: "Search",
    clear: "Clear",
    clearfields: "Clear Fields",
    point: "Point",
    extent: "Extent",
    circle: "Circle",
    polygon: "Polygon",
    freehandPolygon: "Freehand Polygon",
    featuresSelected: "Features selected: ",
    noResults: "No results.",
    searching: "Searching...",
    searchError: "Search failed !",
    and: "and",
    bufferGraphic: 'Buffer Graphic',
    searchDistance: 'Apply a search distance of:',
    applyBuffer: 'Apply Buffer',
    searchEntities: 'To the point:',
    intersectMessage: 'There is no result to intersect, please complete a graphical or text search first.',
    spatialSearchErrorTitle: 'Spatial Search error',
    bufferMessage: 'There is no result to buffer, please complete a graphical or text search first.',
    limit2mapextent: 'Limit search to map extent',
    cancel: 'cancel',
    _continue: 'continue',
    warning: 'Warning!',
    zoomErrorMessage: 'Attempts to auto zoom to the search results have failed.',
    addTextQuery: 'Include text query in selection criteria',
    uniqueValues: 'Retrieving unique values',
    processingUnique: 'Processing unique values: ',
    of: ' of ',
    requiredTip: "Value required to execute search",
    required: "Required",
    requiredWarning: "Required Value Missing",
    requiredErrorMessage: "You have failed to enter one or more required values",
    eLocateTip: "Use Existing Enhanced Locate Widget Graphics",
    createnewselection: "Create new results",
    addtoselection: "Add to current results",
    removefromselection: "Remove from current results"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 1,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  'zh-cn': 0
});
